public enum ComplexBombEvent {

    MODULE_PASSED,
    MODULE_FAILED,

    RESET_TOOLS,
    RELOAD_GAME,

    CASE_OPENED,
    METALPLATE_REMOVED,
    
    TUTORIAL_COMPLETED,
    TUTORIAL_INSTRUCTIONS,
    TUTORIAL_TOOLS,
    TUTORIAL_MENU,
    TUTORIAL_RESET,

    START_COUNTDOWN,
    RIGHT_CABLE_CUTTED,
    WRONG_CABLE_CUTTED
}
